### ISSUE TITLE
The structure of the software is not clearly described in README.md

### ISSUE THREAD

**Issue by khinsen** [Lab-Notebooks/Outflow-Forcing-BubbleML#1]
There are three layers of software in this experiment:
 1. Software that must be already installed.
 2. Software that is installed by `jobrunner setup software`
 3. Software contained in the repository (scripts, Jupyter notebooks, ...)
 
The README starts out by saying that layer 1 contains Jobrunner, ParaView, and BoxKit, hinting at Python 3 being a requirement as well. It mentions FlashKit but doesn't say if it's in layer 1 or in layer 2.

Then, under "usage", it defines layer 1 as containing Jobrunner, MPI, HDF5, and ParaView. But a glance at the "software" directory shows that HDF5 is in layer 2. What happened to BoxKit? More importantly, what happened to everything else that is required beyond MPI to compile/install the programs that are listed? Compilers? Make or CMake?

It would also be helpful for reproducibility to provide version numbers for as much as possible of layer 1. It's rare that results depend on the version of a compiler, but it happens.

**Comment by akashdhruv** [comment]
@khinsen I will fix the README and address these concerns. 

HDF5 is provided in both layers 1 and 2 to allow users to build their own incase they cannot find one already installed on a HPC cluster. Although most HPC and cloud systems would have HDF5 installed, we did find ourselves in a situation where we need to build HDF5 on our own.

**Comment by akashdhruv** [comment]
I have addressed these remarks and updated the README.

**Comment by khinsen** [comment]
Great, thanks! It's a lot clearer now. You are more optimistic than me about "no explicit version constraint for this software", my take is that you cannot know what will happen in the future, but that's probably just because I have been bitten a few times by such problems myself.
