### ISSUE TITLE
Software builds are unlikely to be reproducible

### ISSUE THREAD

**Issue by khinsen** [Lab-Notebooks/Outflow-Forcing-BubbleML#2]
The installation scripts in the `software` directory refer to branches of git repositories, rather than to specific commits or releases. It is impossible to predict what will happen when the code is run a year later. Moreover, what if the repositories are deleted? What if GitHub closes down (as other forges have in the past)?

The most stable and precise references to software are SWHIDs from the [Software Heritage](https://www.softwareheritage.org/) archive.

**Comment by akashdhruv** [comment]
@khinsen If you take a look at `config.sh` at the [ root of the project repository](https://github.com/Lab-Notebooks/Outflow-Forcing-BubbleML/blob/main/config.sh) you will se that we set environment variables for specific SHA-1 that are being used to build the dependencies in `software`.

For Flash-X, SHA-1 values are provided based on each experiment. See [here](https://github.com/Lab-Notebooks/Outflow-Forcing-BubbleML/blob/eedc63d2aba9a8ea670af942b06db9dceb30a04c/simulation/EvaporatingBubble/OutflowTest/outflow/flashBuild.sh#L5).

Design of our experiments has improved over time and you will find that our other [lab notebooks](https://github.com/Lab-Notebooks/ImBound-Mapping-Optimization/blob/main/software/amrex/setupAMReX.sh) have much more cleaner design. 

We will look at SWHIDs and get back to you on that.

**Comment by khinsen** [comment]
@akashdhruv I see it's more complicated than just one-time software setup. Which is fine!

As an example of a SWHID, here is the one for this Lab Notebook repository: [swh:1:snp:052dec5bb38a10035b7a6da3efe4b6dbd4636148;origin=https://github.com/Lab-Notebooks/Outflow-Forcing-BubbleML](https://archive.softwareheritage.org/swh:1:snp:052dec5bb38a10035b7a6da3efe4b6dbd4636148;origin=https://github.com/Lab-Notebooks/Outflow-Forcing-BubbleML)
It's essentially a SHA-1 as well, but resolved in a permanent archive, rather than in a repository that can be changed or deleted.

**Comment by akashdhruv** [comment]
I see. I am trying to figure out how to download archive from SWHID using shell commands.

**Comment by khinsen** [comment]
As far as I know, the only access is the Web API. A combination of `curl` and `jq` should be able to do the job, but I haven't tried.

Software Heritage doesn't want to become to universal download site for software (for reasons of bandwidth), so they don't advertise downloading, nor make it particularly easy. The archive wants to be a backup to be used only when the original reference no longer works. That's how it's used e.g. by the Guix package manager: if a download link fails repeatedly, the SWH archive is used instead.

**Comment by akashdhruv** [comment]
Ok I added a [DEVNOTE for AMReX](https://github.com/Lab-Notebooks/Outflow-Forcing-BubbleML/blob/1ed192d87b897768542e82d16691a76d3bd31555/software/setupAMReX.sh#L3).
